name: Release

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@anmolsudhir'
          cache: pnpm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Create Release PR or Publish Packages
        id: changesets
        uses: changesets/action@v1
        with:
          # Builds the package and executes `changeset publish`
          publish: pnpm release
          # Alias to `changeset version` script in package.json
          version: pnpm version-packages
          commit: 'chore: Updated package versions'
          title: 'chore: Updated package versions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
